Fase3/BreadSpread/BreadSpread/Controllers/ManutencaoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BreadSpread.Models;
using BreadSpread.Controllers;
using System.Net.Mail;
using BreadSpread.Encriptacao;

namespace BreadSpread.Controllers
{
    public class ManutencaoController : Controller
    {
        private BSContext db = new BSContext();

        public ActionResult AdminIndex()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");

            return View("~/Views/Admin/Index.cshtml");
        }

        public ActionResult Perfil()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");

            var User_In_Session = User.Identity.Name;

            var cliente = db.Clientes.Where(c => c.email.Equals(User_In_Session)).ToList();

            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente[0]);
        }

        private void Send(Encomenda e)
        {
            using (MailMessage mm = new MailMessage("breadspread365@gmail.com", User.Identity.Name))
            {
                mm.Subject = "Confirmação de pagamento";
                mm.Body = "O presente email confirma que a encomenda número " + 
                           e.idEnc + " foi paga no dia " + e.dataPag + ".";
                mm.IsBodyHtml = false;
                using (SmtpClient smtp = new SmtpClient())
                {
                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential("breadspread365@gmail.com", "vamosfazerli4");
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = 587;
                    smtp.Send(mm);
                }
            }
        }

        public ActionResult Paga(int id)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");

            Encomenda e = db.Encomendas.Find(id);
            e.dataPag = DateTime.Now;
            e.modoPag = "online";
            e.estado = "confirmada";
            if (ModelState.IsValid)
            {
                db.Entry(e).State = EntityState.Modified;
                db.SaveChanges();
                Send(e);
            }

			return Redirect(Request.UrlReferrer.ToString());
		}

        public ActionResult DesativaCliente(int id)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");

            Cliente c = db.Clientes.Find(id);
            c.estadoConta = "desativado";
            db.Entry(c).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Logout", "Autenticacao");
        }

        public ActionResult PagaEncomendas(int id)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");

            return View(db.Encomendas.Where(enc => enc.idCli.Equals(id) && 
                                            (enc.estado.Equals("pendente") || enc.estado.Equals("confirmada")) && 
                                            enc.dataPag == null)
                                     .ToList());
        }

        public ActionResult EditPerfil(int? id)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPerfil([Bind(Include = "idCli,nome,email,sexo,dataNasc,rua,freguesia,cidade,codPostal,numPorta,contacto,NIF, estadoConta,password")] Cliente cliente)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            //cliente.estadoConta = "ativo";
            Cliente c = db.Clientes.Find(cliente.idCli);
            if (!cliente.password.Equals(c.password))
            {
                cliente.password = MyHelpers.HashPassword(cliente.password);
            }
            db.Entry(c).State = EntityState.Detached;
            //DEIXEI ASSIM PORQUE COM O MODEL STATE NÃO DÁ (COMO ESTÁ INSERE CORRETAMENTE TUDO)
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Perfil");
        }

        public ActionResult Ocasionais()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            var encomendas = db.Encomendas.Where(e => e.estado.Equals("pendente")).ToList();
            /*var encomendas = (from e in db.Encomendas
                            where e.estado == "pendente"
                            select e);*/

            return View(encomendas);
        }

        public ActionResult AceitarEncomenda(int? idEnc)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            if (idEnc == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encomenda encomenda = db.Encomendas.Find(idEnc);
            if (encomenda == null)
            {
                return HttpNotFound();
            }

            encomenda.estado = "confirmada";

            if (ModelState.IsValid)
            {
                db.Entry(encomenda).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Ocasionais");
        }

        public ActionResult RecusarEncomenda(int? idEnc)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            if (idEnc == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encomenda encomenda = db.Encomendas.Find(idEnc);
            if (encomenda == null)
            {
                return HttpNotFound();
            }

            //remoçºao da encomenda em si
            db.Encomendas.Remove(encomenda);

            //remoçºao de todas as entradas associadas à encomenda a remover
            var enc_rem = db.Encomenda_Produto.Where(e => e.idEnc == idEnc).ToList();
            foreach (var m in enc_rem)
                db.Encomenda_Produto.Remove(m);

            db.SaveChanges();

            return RedirectToAction("Ocasionais");
        }

        //==============================
        //========= PRODUTOS ===========
        //==============================

        // GET: Manutencao
        public ActionResult IndexProduto()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            return View(db.Produtoes.ToList());
        }

        // GET: Manutencao/Details/5
        public ActionResult DetailsProduto(int? id)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // GET: Manutencao/Create
        public ActionResult CreateProduto()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            return View();
        }

        // POST: Manutencao/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProduto([Bind(Include = "designacao,ingredientes,infoNutricional,preco,imagem,peso")] Produto produto)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            if (ModelState.IsValid)
            {
                db.Produtoes.Add(produto);
                db.SaveChanges();
                return RedirectToAction("IndexProduto");
            }

            return View(produto);
        }

        // GET: Manutencao/Edit/5
        public ActionResult EditProduto(int? id)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Manutencao/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

Fase3/BreadSpread/BreadSpread/Views/Manutencao/Create.cshtml
@model BreadSpread.Models.Produto

@{
	ViewBag.Title = "Edit";
	Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Alterar</title>

	<!-- Bootstrap Core CSS -->
	<link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

	<!-- MetisMenu CSS -->
	<link href="~/Content/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

	<!-- Custom CSS -->
	<link href="~/Content/dist/css/sb-admin-2.css" rel="stylesheet">

	<!-- Morris Charts CSS -->
	<link href="~/Content/vendor/morrisjs/morris.css" rel="stylesheet">

	<!-- Custom Fonts -->
	<link href="~/Content/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body>

	<div id="wrapper">

		<!-- Navigation -->
		<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="index.html">BreadSpread</a>
			</div>
			<!-- /.navbar-header -->

			<ul class="nav navbar-top-links navbar-right">
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
					</a>
					<ul class="dropdown-menu dropdown-messages">
						<li>
							<a href="#">
								<div>
									<strong>João Silva</strong>
									<span class="pull-right text-muted">
										<em>há 2 min</em>
									</span>
								</div>
								<div>3 pães - sexta às 14h</div>
							</a>
						</li>
						<li class="divider"></li>
						<li>
							<a href="#">
								<div>
									<strong>Miguel Silva</strong>
									<span class="pull-right text-muted">
										<em>há 43 min</em>
									</span>
								</div>
								<div>2 pães - quarta às 21h</div>
							</a>
						</li>
						<li class="divider"></li>
						<li>
							<a class="text-center" href="#">
								<strong>Read All Messages</strong>
								<i class="fa fa-angle-right"></i>
							</a>
						</li>
					</ul>
					<!-- /.dropdown-messages -->
				</li>
				<!-- /.dropdown -->
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
					</a>
					<ul class="dropdown-menu dropdown-tasks">
						<li>
							<a href="#">
								<div>
									<p>
										<strong>Fabrico de produtos</strong>
										<span class="pull-right text-muted">80% Complete</span>
									</p>
									<div class="progress progress-striped active">
										<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
											<span class="sr-only">80% Complete (success)</span>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li class="divider"></li>
						<li>
							<a href="#">
								<div>
									<p>
										<strong>Entregas prontas</strong>
										<span class="pull-right text-muted">65% Complete</span>
									</p>
									<div class="progress progress-striped active">
										<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 65%">
											<span class="sr-only">65% Complete</span>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li class="divider"></li>
						<li>
							<a href="#">
								<div>
									<p>
										<strong>Entregas realizadas</strong>
										<span class="pull-right text-muted">32% Complete</span>
									</p>
									<div class="progress progress-striped active">
										<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 32%">
											<span class="sr-only">32% Complete (warning)</span>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li class="divider"></li>
						<li>
							<a class="text-center" href="#">
								<strong>See All Tasks</strong>
								<i class="fa fa-angle-right"></i>
							</a>
						</li>
					</ul>
					<!-- /.dropdown-tasks -->
				</li>
				<!-- /.dropdown -->
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
					</a>
					<ul class="dropdown-menu dropdown-user">
						<li>
							<a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
						</li>
						<li>
							<a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
						</li>
						<li class="divider"></li>
						<li>
							<a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
						</li>
					</ul>
					<!-- /.dropdown-user -->
				</li>
				<!-- /.dropdown -->
			</ul>
			<!-- /.navbar-top-links -->

			<div class="navbar-default sidebar" role="navigation">
				<div class="sidebar-nav navbar-collapse">
					<ul class="nav" id="side-menu">
						<li>
							<a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Informação Geral</a>
						</li>
						<li>
							<a href="entregas.html"><i class="fa fa-edit fa-fw"></i>Entregas</a>
						</li>
						<li>
							<a href="subscriptions.html"><i class="fa fa-bar-chart-o fa-fw"></i>Subscrições<span class="fa arrow"></span></a>
							<ul class="nav nav-second-level">
								<li>
									<a href="subscriptions.html">Geral</a>
								</li>
								<li>
									<a href="morris.html">Bronze</a>
								</li>
								<li>
									<a href="morris.html">Silver</a>
								</li>
								<li>
									<a href="morris.html">Gold</a>
								</li>
							</ul>
							<!-- /.nav-second-level -->
						</li>
						<li>
							<a href="ocasionais.html"><i class="fa fa-table fa-fw"></i>Entregas ocasionais</a>
						</li>
						<li>
							<a href="vendas.html"><i class="fa fa-wrench fa-fw"></i>Vendas</a>
						</li>
						<li>
							<a href="produtos.html"><i class="fa fa-sitemap fa-fw"></i>Lista Produtos</a>
						</li>
						<li>
							<a href="../../breadstrap/index.html"> <img alt="" class="mb-2" height="220" src="./images/logo.png"></a>
						</li>
					</ul>
				</div>
				<!-- /.sidebar-collapse -->
			</div>
			<!-- /.navbar-static-side -->
		</nav>

		<div id="page-wrapper">
			<div class="row">
				<div class="col-lg-12">
					<h1 class="page-header">Produtos</h1>
				</div>
				<!-- /.col-lg-12 -->
			</div>
			<!-- /.row -->
			<div class="row">
				<div class="col-lg-12">
					<div class="panel panel-default ">
						<div class="panel-heading">
							<div class="row">
								<div class="col-sm-10 align-middle">
									Todos os Produtos
								</div>
								<div class="col-sm-2">
									<button type="button" class="btn btn-success pt-3">Adicionar</button>
								</div>
							</div>
						</div>
						<!-- /.panel-heading -->
						<div class="panel-body">
							@using (Html.BeginForm("Create", "Manutencao", FormMethod.Post))
							{
								@Html.AntiForgeryToken()

							<div class="form-horizontal">
								<h4>Produto</h4>
								<hr />

								<div class="form-group">
									@Html.LabelFor(model => model.idProd, htmlAttributes: new { @class = "control-label col-md-2" })
									<div class="col-md-10">
										@Html.EditorFor(model => model.idProd, new { htmlAttributes = new { @class = "form-control" } })
										@Html.ValidationMessageFor(model => model.designacao, "", new { @class = "text-danger" })
									</div>
								</div>

								<div class="form-group">
									@Html.LabelFor(model => model.designacao, htmlAttributes: new { @class = "control-label col-md-2" })
									<div class="col-md-10">
										@Html.EditorFor(model => model.designacao, new { htmlAttributes = new { @class = "form-control" } })
										@Html.ValidationMessageFor(model => model.designacao, "", new { @class = "text-danger" })
									</div>
								</div>

								<div class="form-group">
									@Html.LabelFor(model => model.ingredientes, htmlAttributes: new { @class = "control-label col-md-2" })
									<div class="col-md-10">
										@Html.EditorFor(model => model.ingredientes, new { htmlAttributes = new { @class = "form-control" } })
										@Html.ValidationMessageFor(model => model.ingredientes, "", new { @class = "text-danger" })
									</div>
								</div>

								<div class="form-group">
									@Html.LabelFor(model => model.infoNutricional, htmlAttributes: new { @class = "control-label col-md-2" })
									<div class="col-md-10">
										@Html.EditorFor(model => model.infoNutricional, new { htmlAttributes = new { @class = "form-control" } })
										@Html.ValidationMessageFor(model => model.infoNutricional, "", new { @class = "text-danger" })
									</div>
								</div>

								<div class="form-group">
									@Html.LabelFor(model => model.preco, htmlAttributes: new { @class = "control-label col-md-2" })
									<div class="col-md-10">
										@Html.EditorFor(model => model.preco, new { htmlAttributes = new { @class = "form-control" } })
										@Html.ValidationMessageFor(model => model.preco, "", new { @class = "text-danger" })
									</div>
								</div>

								<div class="form-group">
									@Html.LabelFor(model => model.imagem, htmlAttributes: new { @class = "control-label col-md-2" })
									<div class="col-md-10">
										@Html.EditorFor(model => model.imagem, new { htmlAttributes = new { @class = "form-control" } })
										@Html.ValidationMessageFor(model => model.imagem, "", new { @class = "text-danger" })
									</div>
								</div>

								<div class="form-group">
									@Html.LabelFor(model => model.peso, htmlAttributes: new { @class = "control-label col-md-2" })
									<div class="col-md-10">
										@Html.EditorFor(model => model.peso, new { htmlAttributes = new { @class = "form-control" } })
										@Html.ValidationMessageFor(model => model.peso, "", new { @class = "text-danger" })
									</div>
								</div>

								<div class="form-group">
									<div class="col-md-offset-2 col-md-10">
										<input type="submit" value="Create" class="btn btn-success btn-lg" />
										@Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-lg btn-primary" })
									</div>
								</div>
							</div>
							}

						</div>
						<!-- /.panel-body -->
					</div>
					<!-- /.panel -->
				</div>
				<!-- /.col-lg-12 -->
			</div>

		</div>
		<!-- /#page-wrapper -->

	</div>
	<!-- /#wrapper -->
	<!-- jQuery -->
	<script src="~/content/vendor/jquery/jquery.min.js"></script>

	<!-- Bootstrap Core JavaScript -->
	<script src="~/content/vendor/bootstrap/js/bootstrap.min.js"></script>

	<!-- Metis Menu Plugin JavaScript -->
	<script src="~/content/vendor/metisMenu/metisMenu.min.js"></script>

	<!-- Morris Charts JavaScript -->
	<script src="~/content/vendor/raphael/raphael.min.js"></script>
	<script src="~/Content/vendor/morrisjs/morris.min.js"></script>
	<script src="data/morris-data.js"></script>

	<!-- Custom Theme JavaScript -->
	<script src="~/Content/dist/js/sb-admin-2.js"></script>

</body>

</html>

Fase3/BreadSpread/BreadSpread/Views/Manutencao/CreateFuncionario.cshtml
@model BreadSpread.Models.Funcionario

@{
	ViewBag.Title = "CreateFuncionario";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


		<div id="page-wrapper">
			<div class="row">
				<div class="col-lg-12">
					<h1 class="page-header">Produto</h1>
				</div>
				<!-- /.col-lg-12 -->
			</div>
			<!-- /.row -->
			<div class="row">
				<div class="col-lg-12">
					<div class="panel panel-default ">
						<!-- /.panel-heading -->
						<div class="panel-body">
							@using (Html.BeginForm("CreateFuncionario", "Manutencao", FormMethod.Post))
							{
								@Html.AntiForgeryToken()

								<div class="form-horizontal">
									<h4>@Html.DisplayFor(model => model.nome)</h4>
									<hr />

									<div class="form-group">
										@Html.LabelFor(model => model.idFunc, htmlAttributes: new { @class = "control-label col-md-2" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.idFunc, new { htmlAttributes = new { @class = "form-control", type = "text" } })
											@Html.ValidationMessageFor(model => model.idFunc, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control", type = "text" } })
											@Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.dataNasc, htmlAttributes: new { @class = "control-label col-md-2" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.dataNasc, new { htmlAttributes = new { @class = "form-control", type = "date" } })
											@Html.ValidationMessageFor(model => model.dataNasc, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.contacto, htmlAttributes: new { @class = "control-label col-md-2" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.contacto, new { htmlAttributes = new { @class = "form-control", type = "number" } })
											@Html.ValidationMessageFor(model => model.contacto, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.rua, htmlAttributes: new { @class = "control-label col-md-2" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.rua, new { htmlAttributes = new { @class = "form-control", type = "text" } })
											@Html.ValidationMessageFor(model => model.rua, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.numPorta, htmlAttributes: new { @class = "control-label col-md-2" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.numPorta, new { htmlAttributes = new { @class = "form-control", type = "number" } })
											@Html.ValidationMessageFor(model => model.numPorta, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.codPostal, htmlAttributes: new { @class = "control-label col-md-2" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.codPostal, new { htmlAttributes = new { @class = "form-control", type = "text" } })
											@Html.ValidationMessageFor(model => model.codPostal, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.cidade, htmlAttributes: new { @class = "control-label col-md-2" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.cidade, new { htmlAttributes = new { @class = "form-control", type = "text" } })
											@Html.ValidationMessageFor(model => model.cidade, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", type = "password" } })
											@Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.estadoConta, htmlAttributes: new { @class = "control-label col-md-2" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.estadoConta, new { htmlAttributes = new { @class = "form-control", type = "text" } })
											@Html.ValidationMessageFor(model => model.estadoConta, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.distribuicao, htmlAttributes: new { @class = "control-label col-md-2" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.distribuicao, new { htmlAttributes = new { @class = "form-control", type = "text" } })
											@Html.ValidationMessageFor(model => model.distribuicao, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.freguesia, htmlAttributes: new { @class = "control-label col-md-2", type = "text" })
										<div class="col-md-10">
											@Html.EditorFor(model => model.freguesia, new { htmlAttributes = new { @class = "form-control" } })
											@Html.ValidationMessageFor(model => model.freguesia, "", new { @class = "text-danger" })
										</div>
									</div>

									<div class="form-group">
										<div class="col-md-offset-2 col-md-10">
											<input type="submit" value="Adicionar" class="btn btn-success btn-lg" />
											@Html.ActionLink("Voltar", "IndexFuncionario", null, new { @class = "btn btn-lg btn-primary" })
										</div>
									</div>
								</div>
							}

						</div>
						<!-- /.panel-body -->
					</div>
					<!-- /.panel -->
				</div>
				<!-- /.col-lg-12 -->
			</div>

		</div>
		<!-- /#page-wrapper -->

	