Fase3/BreadSpread/BreadSpread/Controllers/RealizacaoController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.Serialization.Json;
using System.Web.Mvc;
using BreadSpread.Models;
using BingMapsRESTToolkit;
using System.IO;
using System.Text;
using System.Collections;

namespace BreadSpread.Controllers
{
    public class LatLong
    {
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }

    public class RealizacaoController : Controller
    {
        private BSContext db = new BSContext();

        public ActionResult PadeiroIndex()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            return View("~/Views/Padeiro/Index.cshtml");
        }

        public ActionResult EstafetaIndex()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            return View("~/Views/Estafeta/Index.cshtml");
        }

        public ActionResult RegistaEntrega(int idEnc)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            Encomenda enc_db = db.Encomendas.Find(idEnc);
            enc_db.estado = "entregue";
            if (ModelState.IsValid)
            {
                db.Entry(enc_db).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Percurso");
        }
        public ActionResult CancelaEntrega(int idEnc, string obs)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            Encomenda enc_db = db.Encomendas.Find(idEnc);
            enc_db.estado = "falhada";
            enc_db.obs = obs;
            if (ModelState.IsValid)
            {
                db.Entry(enc_db).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Percurso");
        }

        public static LatLong Geocode(string address)
        {
            string url = "http://dev.virtualearth.net/REST/v1/Locations?query=" + address + "&key=Arf-w6Z0c3_4-bcaAuGaelwSAFWNaomV1EN1N7PG18GbR5raQUIhfeswUtFi6_Ze";

            using (var client = new WebClient())
            {
                string response = client.DownloadString(url);
                DataContractJsonSerializer ser = new DataContractJsonSerializer(typeof(Response));
                using (var es = new MemoryStream(Encoding.Unicode.GetBytes(response)))
                {
                    var mapResponse = (ser.ReadObject(es) as Response); //Response is one of the Bing Maps DataContracts
                    Location location = (Location)mapResponse.ResourceSets.First().Resources.First();
                    return new LatLong()
                    {
                        Latitude = location.Point.Coordinates[0],
                        Longitude = location.Point.Coordinates[1]
                    };
                }
            }
        }

        public ActionResult Percurso()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");

            var encomendas = db.Encomendas.Where(e => e.estado.Equals("confecionada") &&
                                                      e.dataPag != null)
                                          .ToList();
            var encomendas_hoje = encomendas.Where(e => e.dataEnt.Date == DateTime.Now.Date).ToList();

            var coordsLat = new ArrayList();
            var coordsLon = new ArrayList();
            var labelEncs = new ArrayList();

            foreach(var enc in encomendas_hoje)
            {
                LatLong coord = Geocode(enc.Cliente.rua + "," +
                                        enc.Cliente.numPorta + "," +
                                        enc.Cliente.freguesia + "," +
                                        enc.Cliente.codPostal + "," +
                                        enc.Cliente.cidade + ", Portugal");
                coordsLat.Add(coord.Latitude);
                coordsLon.Add(coord.Longitude);
                labelEncs.Add(enc.idEnc);
            }

            ViewBag.coordsLat = coordsLat;
            ViewBag.coordsLon = coordsLon;
            ViewBag.labelEncs = labelEncs;

            return View(encomendas_hoje);
        }


        public ActionResult CheckProduto(int idEnc, int idProd)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            var enc_prod_atual = db.Encomenda_Produto.Find(idEnc, idProd);
            if (enc_prod_atual != null)
            {
                enc_prod_atual.estado = "feito";
                if (ModelState.IsValid)
                {
                    db.Entry(enc_prod_atual).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }

            var encomendas = db.Encomenda_Produto.Where(ep => ep.Encomenda.estado.Equals("confirmada") && 
                                                              ep.Encomenda.dataEnt != null &&
                                                              ep.idEnc == idEnc && 
                                                              ep.estado.Equals("pendente"))
                                                 .ToList();
            var num_encomendas_hoje = encomendas.Where(ep => ep.Encomenda.dataEnt.Date == DateTime.Now.Date ).ToList().Count;

            if (num_encomendas_hoje == 0)
            {
                Encomenda encomenda = db.Encomendas.Find(idEnc);
                if (encomenda == null)
                {
                    return RedirectToAction("IndexProducao", "Pesquisa");
                }
                encomenda.estado = "confecionada";
                if (ModelState.IsValid)
                {
                    db.Entry(encomenda).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("IndexProducao", "Pesquisa");
        }
















        //// GET: Realizacao
        //public ActionResult IndexProducao()
        //{
        //    var encomendas = db.Encomendas.Include(e => e.Cliente);
        //    return View(encomendas.ToList());
        //}

        // GET: Realizacao/Details/5
        public ActionResult DetailsEncomenda(int? id)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encomenda encomenda = db.Encomendas.Find(id);
            if (encomenda == null)
            {
                return HttpNotFound();
            }
            return View(encomenda);
        }

        // GET: Realizacao/Create
        public ActionResult CreateEncomenda()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            ViewBag.idCli = new SelectList(db.Clientes, "idCli", "nome");
            return View();
        }

        // POST: Realizacao/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateEncomenda([Bind(Include = "idEnc,idCli,dataEnt,custo,estado,idFunc,rua,numPorta,codPostal,cidade,obs,freguesia,tipoEnc,dataPag,modoPag,fatura")] Encomenda encomenda)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            if (ModelState.IsValid)
            {
                db.Encomendas.Add(encomenda);
                db.SaveChanges();
                return RedirectToAction("IndexEncomenda");
            }

            ViewBag.idCli = new SelectList(db.Clientes, "idCli", "nome", encomenda.idCli);
            return View(encomenda);
        }

        // GET: Realizacao/Edit/5
        public ActionResult EditEncomenda(int? id)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encomenda encomenda = db.Encomendas.Find(id);
            if (encomenda == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCli = new SelectList(db.Clientes, "idCli", "nome", encomenda.idCli);
            return View(encomenda);
        }

        // POST: Realizacao/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditEncomenda([Bind(Include = "idEnc,idCli,dataEnt,custo,estado,idFunc,rua,numPorta,codPostal,cidade,obs,freguesia,tipoEnc,dataPag,modoPag,fatura")] Encomenda encomenda)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Autenticacao");
            if (ModelState.IsValid)
            {
                db.Entry(encomenda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexEncomenda");
            }
            ViewBag.idCli = new SelectList(db.Clientes, "idCli", "nome", encomenda.idCli);
            return View(encomenda);
        }

        // GET: Realizacao/Delete/5
        public ActionResult DeleteEncomenda(int? id)
        {
            if (!User.Identity.IsAuthenticated)

Fase3/BreadSpread/BreadSpread/Views/Realizacao/Create.cshtml
@model BreadSpread.Models.Encomenda

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Encomenda</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idCli, "idCli", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCli", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCli, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dataEnt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dataEnt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dataEnt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.custo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.custo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.custo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idFunc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idFunc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idFunc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rua, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rua, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rua, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numPorta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numPorta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numPorta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.codPostal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codPostal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codPostal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.obs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.obs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.obs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.freguesia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.freguesia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freguesia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipoEnc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tipoEnc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tipoEnc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dataPag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dataPag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dataPag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modoPag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.modoPag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.modoPag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fatura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fatura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fatura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Fase3/BreadSpread/BreadSpread/Views/Realizacao/Delete.cshtml
@model BreadSpread.Models.Encomenda

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Encomenda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dataEnt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dataEnt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.custo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.custo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.idFunc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idFunc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rua)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numPorta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numPorta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.codPostal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codPostal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.obs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.obs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freguesia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freguesia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipoEnc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipoEnc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dataPag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dataPag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modoPag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modoPag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fatura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fatura)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Fase3/BreadSpread/BreadSpread/Views/Realizacao/Details.cshtml
@model BreadSpread.Models.Encomenda

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Encomenda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dataEnt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dataEnt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.custo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.custo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.idFunc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idFunc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rua)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numPorta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numPorta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.codPostal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codPostal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.obs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.obs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freguesia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freguesia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipoEnc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipoEnc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dataPag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dataPag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modoPag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modoPag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fatura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fatura)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idEnc }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Fase3/BreadSpread/BreadSpread/Views/Realizacao/Percurso.cshtml
@model IEnumerable<BreadSpread.Models.Encomenda>

@{
    ViewBag.Title = "Percurso";
	/*If admin ou estafeta*/
    Layout = "~/Views/Shared/_EstafetaLayout.cshtml";
}

    <script type='text/javascript'
            src='http://www.bing.com/api/maps/mapcontrol?callback=GetMap'
            async defer></script>
    <script type='text/javascript'>
        function GetMap() {

            var coordsLat = @Html.Raw(Json.Encode(@ViewBag.coordsLat));
            var coordsLon = @Html.Raw(Json.Encode(@ViewBag.coordsLon));
            var labelEncs = @Html.Raw(Json.Encode(@ViewBag.labelEncs));

            var map = new Microsoft.Maps.Map('#myMap', {
                credentials: 'Arf-w6Z0c3_4-bcaAuGaelwSAFWNaomV1EN1N7PG18GbR5raQUIhfeswUtFi6_Ze',
                center: new Microsoft.Maps.Location(coordsLat[0], coordsLon[0])
            });

            var center = map.getCenter();

            for (var i = 0; i < coordsLat.length; i++) {
                //Create custom Pushpin
                var pin = new Microsoft.Maps.Pushpin(new Microsoft.Maps.Location(coordsLat[i], coordsLon[i]), {
                    text: labelEncs[i].toString()
                });

                //Add the pushpin to the map
                map.entities.push(pin);
            }
        }
    </script>



        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Percurso</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-7">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bar-chart-o fa-fw"></i> Encomendas a entregar
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="myMap" style="position:relative;width:885px;height:500px;"></div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                    
                </div>
                <!-- /.col-lg-12 -->
                <div class="col-lg-5">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bar-chart-o fa-fw"></i> Dados da próxima entrega
                        </div>
                        
                        <div class="panel-body">
                            @using (Html.BeginForm("RegistaEntrega", "Realizacao", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                if (Model.Count() != 0)
                                {
                                    <div class="pull-right">
                                        <input type="hidden" name="idEnc" value=@Model.First().idEnc />
                                        <input type="submit" value="Entregue" class="btn btn-success btn-lg" />
                                    </div>
                                }
                            }

                            @if (Model.Count() != 0)
                            {
                                <h4>@Model.First().Cliente.nome</h4>
                                <p>@Model.First().rua, nº @Model.First().numPorta, @Model.First().codPostal, @Model.First().freguesia</p>
                                <p>@Model.First().idEnc</p>
                                @*<button type="button" class="btn btn-success btn-lg">Pagar</button>*@
                            }
                            else
                            {
                                <h4>Todas as entregas encontram-se realizadas!</h4>
                            }
                            @using (Html.BeginForm("CancelaEntrega", "Realizacao", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                if (Model.Count() != 0)
                                {
                                    <hr/>
                                    <div class="form-group">
                                        <label>Observações</label>
                                        @Html.TextArea("obs", new { @class = "form-control", @rows = "3" })
                                    </div>  
                                    <div class="pull-right">
                                        <input type="hidden" name="idEnc" value=@Model.First().idEnc />
                                        <input type="submit" value="Falha" class="btn btn-danger btn-lg" />
                                    </div>
                                }
                            }
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Lista de Entregas do Percurso 
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body">
                                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Nome</th>
                                            <th>Morada</th>
                                            <th>Hora</th>
                                            <th>Encomenda #</th>
                                            <th>Estado</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr class="odd gradeX">
                                                <th>@Html.DisplayFor(modelItem => item.Cliente.nome)</th>
                                                <th>@item.rua, nº @item.numPorta, @item.codPostal, @item.freguesia</th>
                                                <td>@Html.DisplayFor(modelItem => item.dataEnt.Hour)</td>
                                                <td>@Html.DisplayFor(modelItem => item.idEnc)</td>
                                                <td>@Html.DisplayFor(modelItem => item.estado)</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.panel-body -->
                        </div>
                        <!-- /.panel -->
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    